export const appUrls: { [key: string]: string } = {
  'Browser': 'https://www.google.com',
  'Mail': 'https://mail.google.com',
  'Calendar': 'https://calendar.google.com',
  'Maps': 'https://www.google.com/maps',
  'YouTube': 'https://www.youtube.com',
  'Weather': 'https://www.accuweather.com',
  'Notes': 'https://keep.google.com',
  'Calculator': 'https://www.desmos.com/scientific',
  'Photos': 'https://photos.google.com',
  'Music': 'https://artopia.dev',
  'Finder': 'https://www.icloud.com',
  'Terminal': 'https://bellard.org/jslinux/vm.html?url=alpine-x86.cfg&mem=192',
  'Settings': 'https://www.icloud.com/settings',
  'App Store': 'https://www.apple.com/app-store',
  'FaceTime': 'https://www.icloud.com',
  'Messages': 'https://www.icloud.com',
  'Contacts': 'https://www.icloud.com/contacts',
  'Reminders': 'https://www.icloud.com/reminders',
  'Podcasts': 'https://www.apple.com/apple-podcasts',
  'TV': 'https://www.apple.com/apple-tv-plus',
  'Books': 'https://www.apple.com/apple-books',
  'Pages': 'https://www.icloud.com/pages',
  'Numbers': 'https://www.icloud.com/numbers',
  'Keynote': 'https://www.icloud.com/keynote',
  'GarageBand': 'https://www.apple.com/mac/garageband',
  'iMovie': 'https://www.apple.com/imovie',
  'Font Book': 'https://support.apple.com/guide/font-book/welcome/mac',
  'Dictionary': 'https://www.merriam-webster.com',
  'Voice Memos': 'https://support.apple.com/guide/voice-memos/welcome/mac',
  'Stocks': 'https://finance.yahoo.com',
  'Home': 'https://www.apple.com/ios/home',
  'Chess': 'https://www.chess.com',
  'Stickies': 'https://support.apple.com/guide/stickies/welcome/mac',
  'TextEdit': 'https://support.apple.com/guide/textedit/welcome/mac',
  'QuickTime Player': 'https://support.apple.com/quicktime',
  'Preview': 'https://support.apple.com/guide/preview/welcome/mac',
  'Activity Monitor': 'https://support.apple.com/guide/activity-monitor/welcome/mac',
  'Disk Utility': 'https://support.apple.com/guide/disk-utility/welcome/mac',
  'Console': 'https://support.apple.com/guide/console/welcome/mac',
  'Script Editor': 'https://support.apple.com/guide/script-editor/welcome/mac',
  'Signup': 'https://example.com/signup',
  'About': 'https://example.com/about',
  'Play': 'https://example.com/play',
  'Folder': 'https://example.com/folder',
  'Wallet': 'https://example.com/wallet',
  'User': 'https://example.com/user',
  'ShoppingBag': 'https://example.com/shop',
  'Search': 'https://www.google.com',
  // 'dApp Store' is not included here as it's handled separately
};